// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package spec

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApplicationMetadata_ApplicationProtocol int32

const (
	ApplicationMetadata_http  ApplicationMetadata_ApplicationProtocol = 0
	ApplicationMetadata_https ApplicationMetadata_ApplicationProtocol = 1
)

var ApplicationMetadata_ApplicationProtocol_name = map[int32]string{
	0: "http",
	1: "https",
}

var ApplicationMetadata_ApplicationProtocol_value = map[string]int32{
	"http":  0,
	"https": 1,
}

func (x ApplicationMetadata_ApplicationProtocol) String() string {
	return proto.EnumName(ApplicationMetadata_ApplicationProtocol_name, int32(x))
}

func (ApplicationMetadata_ApplicationProtocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0, 0}
}

type ApplicationMetadata struct {
	ApplicationName      string                                  `protobuf:"bytes,1,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	ApplicationVersion   string                                  `protobuf:"bytes,2,opt,name=application_version,json=applicationVersion,proto3" json:"application_version,omitempty"`
	HelmchartName        string                                  `protobuf:"bytes,3,opt,name=helmchart_name,json=helmchartName,proto3" json:"helmchart_name,omitempty"`
	HelmchartVersion     string                                  `protobuf:"bytes,4,opt,name=helmchart_version,json=helmchartVersion,proto3" json:"helmchart_version,omitempty"`
	CnabspecVersion      string                                  `protobuf:"bytes,5,opt,name=cnabspec_version,json=cnabspecVersion,proto3" json:"cnabspec_version,omitempty"`
	ComposeVersion       string                                  `protobuf:"bytes,6,opt,name=compose_version,json=composeVersion,proto3" json:"compose_version,omitempty"`
	ClusterName          string                                  `protobuf:"bytes,7,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	K8SVersionSupported  string                                  `protobuf:"bytes,8,opt,name=k8s_version_supported,json=k8sVersionSupported,proto3" json:"k8s_version_supported,omitempty"`
	ApplicationProtocol  ApplicationMetadata_ApplicationProtocol `protobuf:"varint,9,opt,name=application_protocol,json=applicationProtocol,proto3,enum=SMPS.ApplicationMetadata_ApplicationProtocol" json:"application_protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *ApplicationMetadata) Reset()         { *m = ApplicationMetadata{} }
func (m *ApplicationMetadata) String() string { return proto.CompactTextString(m) }
func (*ApplicationMetadata) ProtoMessage()    {}
func (*ApplicationMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}

func (m *ApplicationMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationMetadata.Unmarshal(m, b)
}
func (m *ApplicationMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationMetadata.Marshal(b, m, deterministic)
}
func (m *ApplicationMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationMetadata.Merge(m, src)
}
func (m *ApplicationMetadata) XXX_Size() int {
	return xxx_messageInfo_ApplicationMetadata.Size(m)
}
func (m *ApplicationMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationMetadata proto.InternalMessageInfo

func (m *ApplicationMetadata) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *ApplicationMetadata) GetApplicationVersion() string {
	if m != nil {
		return m.ApplicationVersion
	}
	return ""
}

func (m *ApplicationMetadata) GetHelmchartName() string {
	if m != nil {
		return m.HelmchartName
	}
	return ""
}

func (m *ApplicationMetadata) GetHelmchartVersion() string {
	if m != nil {
		return m.HelmchartVersion
	}
	return ""
}

func (m *ApplicationMetadata) GetCnabspecVersion() string {
	if m != nil {
		return m.CnabspecVersion
	}
	return ""
}

func (m *ApplicationMetadata) GetComposeVersion() string {
	if m != nil {
		return m.ComposeVersion
	}
	return ""
}

func (m *ApplicationMetadata) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *ApplicationMetadata) GetK8SVersionSupported() string {
	if m != nil {
		return m.K8SVersionSupported
	}
	return ""
}

func (m *ApplicationMetadata) GetApplicationProtocol() ApplicationMetadata_ApplicationProtocol {
	if m != nil {
		return m.ApplicationProtocol
	}
	return ApplicationMetadata_http
}

func init() {
	proto.RegisterEnum("SMPS.ApplicationMetadata_ApplicationProtocol", ApplicationMetadata_ApplicationProtocol_name, ApplicationMetadata_ApplicationProtocol_value)
	proto.RegisterType((*ApplicationMetadata)(nil), "SMPS.ApplicationMetadata")
}

func init() {
	proto.RegisterFile("metadata.proto", fileDescriptor_56d9f74966f40d04)
}

var fileDescriptor_56d9f74966f40d04 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xad, 0xfb, 0xe1, 0xfa, 0xa6, 0x5d, 0x4d, 0x15, 0x7a, 0x9c, 0x03, 0x71, 0x53, 0xac,
	0x30, 0x2f, 0x03, 0x4f, 0x7a, 0x9f, 0x8c, 0x15, 0x3c, 0x78, 0x99, 0x59, 0x16, 0x68, 0x59, 0xdb,
	0x84, 0x26, 0xf3, 0xcf, 0x17, 0xe9, 0x6b, 0xd3, 0x45, 0xf0, 0x52, 0xca, 0xe7, 0x7d, 0xf2, 0xe5,
	0xf1, 0xbe, 0xe0, 0xe5, 0x5c, 0xd3, 0x1d, 0xd5, 0x34, 0x92, 0xa5, 0xd0, 0x82, 0x74, 0xe3, 0xe5,
	0x2a, 0x9e, 0xfc, 0x74, 0x20, 0x78, 0x95, 0x32, 0x4b, 0x19, 0xd5, 0xa9, 0x28, 0x96, 0x8d, 0x43,
	0x66, 0xe0, 0xd3, 0x23, 0xde, 0x14, 0x34, 0xe7, 0xa1, 0x33, 0x76, 0xa6, 0xee, 0x7a, 0x64, 0xf1,
	0x77, 0x9a, 0x73, 0xf2, 0x04, 0x81, 0xad, 0x7e, 0xf3, 0x52, 0xa5, 0xa2, 0x08, 0x4f, 0xd1, 0x26,
	0xd6, 0xe8, 0xa3, 0x9e, 0x90, 0x5b, 0xf0, 0x12, 0x9e, 0xe5, 0x2c, 0xa1, 0xa5, 0xae, 0x93, 0x3b,
	0xe8, 0x5e, 0xb4, 0x14, 0x73, 0x1f, 0xe0, 0xf2, 0xa8, 0x99, 0xd4, 0x2e, 0x9a, 0x7e, 0x3b, 0x30,
	0x99, 0x33, 0xf0, 0x59, 0x41, 0xb7, 0x4a, 0x72, 0xd6, 0xba, 0xbd, 0x7a, 0x5f, 0xc3, 0x8d, 0x7a,
	0x07, 0x23, 0x26, 0x72, 0x29, 0x14, 0x6f, 0xcd, 0x3e, 0x9a, 0x5e, 0x83, 0x8d, 0x78, 0x03, 0xe7,
	0x2c, 0x3b, 0x28, 0xcd, 0xcb, 0x7a, 0xcb, 0x33, 0xb4, 0x86, 0x0d, 0xc3, 0x1d, 0xe7, 0x70, 0xbd,
	0x5f, 0x28, 0x93, 0xb3, 0x51, 0x07, 0x29, 0x45, 0xa9, 0xf9, 0x2e, 0x1c, 0xa0, 0x1b, 0xec, 0x17,
	0xaa, 0x49, 0x8b, 0xcd, 0x88, 0x7c, 0xc1, 0x95, 0x7d, 0x2f, 0x6c, 0x83, 0x89, 0x2c, 0x74, 0xc7,
	0xce, 0xd4, 0x9b, 0x3f, 0x46, 0x55, 0x2f, 0xd1, 0x3f, 0x9d, 0xd8, 0x6c, 0xd5, 0x3c, 0x5a, 0xdb,
	0xa7, 0x37, 0x70, 0x72, 0xff, 0xa7, 0x53, 0x83, 0xc9, 0x00, 0xba, 0x89, 0xd6, 0xd2, 0x3f, 0x21,
	0x2e, 0xf4, 0xaa, 0x3f, 0xe5, 0x3b, 0x6f, 0xc3, 0x4f, 0xb7, 0x3a, 0xce, 0x4b, 0xf5, 0xd9, 0xf6,
	0x71, 0x99, 0xe7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x40, 0x54, 0x7e, 0x2d, 0x2c, 0x02, 0x00,
	0x00,
}
