// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package spec

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApplicationMetadataApplicationProtocol int32

const (
	ApplicationMetadata_http  ApplicationMetadataApplicationProtocol = 0
	ApplicationMetadata_https ApplicationMetadataApplicationProtocol = 1
)

var ApplicationMetadataApplicationProtocol_name = map[int32]string{
	0: "http",
	1: "https",
}

var ApplicationMetadataApplicationProtocol_value = map[string]int32{
	"http":  0,
	"https": 1,
}

func (x ApplicationMetadataApplicationProtocol) String() string {
	return proto.EnumName(ApplicationMetadataApplicationProtocol_name, int32(x))
}

func (ApplicationMetadataApplicationProtocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0, 0}
}

type ApplicationMetadata struct {
	ApplicationName      string   `protobuf:"bytes,1,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	ApplicationVersion   string   `protobuf:"bytes,2,opt,name=application_version,json=applicationVersion,proto3" json:"application_version,omitempty"`
	HelmchartName        string   `protobuf:"bytes,3,opt,name=helmchart_name,json=helmchartName,proto3" json:"helmchart_name,omitempty"`
	HelmchartVersion     string   `protobuf:"bytes,4,opt,name=helmchart_version,json=helmchartVersion,proto3" json:"helmchart_version,omitempty"`
	CnabspecVersion      string   `protobuf:"bytes,5,opt,name=cnabspec_version,json=cnabspecVersion,proto3" json:"cnabspec_version,omitempty"`
	ComposeVersion       string   `protobuf:"bytes,6,opt,name=compose_version,json=composeVersion,proto3" json:"compose_version,omitempty"`
	ClusterName          string   `protobuf:"bytes,7,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	K8SVersionSupported  string   `protobuf:"bytes,8,opt,name=k8s_version_supported,json=k8sVersionSupported,proto3" json:"k8s_version_supported,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationMetadata) Reset()         { *m = ApplicationMetadata{} }
func (m *ApplicationMetadata) String() string { return proto.CompactTextString(m) }
func (*ApplicationMetadata) ProtoMessage()    {}
func (*ApplicationMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}

func (m *ApplicationMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationMetadata.Unmarshal(m, b)
}
func (m *ApplicationMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationMetadata.Marshal(b, m, deterministic)
}
func (m *ApplicationMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationMetadata.Merge(m, src)
}
func (m *ApplicationMetadata) XXX_Size() int {
	return xxx_messageInfo_ApplicationMetadata.Size(m)
}
func (m *ApplicationMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationMetadata proto.InternalMessageInfo

func (m *ApplicationMetadata) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *ApplicationMetadata) GetApplicationVersion() string {
	if m != nil {
		return m.ApplicationVersion
	}
	return ""
}

func (m *ApplicationMetadata) GetHelmchartName() string {
	if m != nil {
		return m.HelmchartName
	}
	return ""
}

func (m *ApplicationMetadata) GetHelmchartVersion() string {
	if m != nil {
		return m.HelmchartVersion
	}
	return ""
}

func (m *ApplicationMetadata) GetCnabspecVersion() string {
	if m != nil {
		return m.CnabspecVersion
	}
	return ""
}

func (m *ApplicationMetadata) GetComposeVersion() string {
	if m != nil {
		return m.ComposeVersion
	}
	return ""
}

func (m *ApplicationMetadata) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *ApplicationMetadata) GetK8SVersionSupported() string {
	if m != nil {
		return m.K8SVersionSupported
	}
	return ""
}

func init() {
	proto.RegisterEnum("SMPS.ApplicationMetadataApplicationProtocol", ApplicationMetadataApplicationProtocol_name, ApplicationMetadataApplicationProtocol_value)
	proto.RegisterType((*ApplicationMetadata)(nil), "SMPS.ApplicationMetadata")
}

func init() {
	proto.RegisterFile("metadata.proto", fileDescriptor_56d9f74966f40d04)
}

var fileDescriptor_56d9f74966f40d04 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd1, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0x06, 0x70, 0xeb, 0xba, 0xb9, 0xbe, 0x69, 0x17, 0x53, 0x85, 0x1e, 0x75, 0x20, 0x3a, 0x06,
	0x0a, 0x7a, 0x19, 0x78, 0xd2, 0xfb, 0x44, 0x2c, 0x78, 0xf0, 0x32, 0xb2, 0x2c, 0xd0, 0xb2, 0xa6,
	0x09, 0x49, 0xe6, 0x7f, 0xe3, 0xff, 0x2a, 0x7d, 0x6d, 0xda, 0x5e, 0x4a, 0xf9, 0xde, 0x8f, 0x8f,
	0x8f, 0x16, 0x62, 0x29, 0x1c, 0xdb, 0x33, 0xc7, 0x1e, 0xb5, 0x51, 0x4e, 0xd1, 0x30, 0xdb, 0x7c,
	0x66, 0x8b, 0xbf, 0x11, 0x24, 0x6f, 0x5a, 0x97, 0x05, 0x67, 0xae, 0x50, 0xd5, 0xa6, 0x35, 0x74,
	0x09, 0x84, 0xf5, 0xf1, 0xb6, 0x62, 0x52, 0xa4, 0xc1, 0x4d, 0xf0, 0x10, 0x7d, 0xcd, 0x07, 0xf9,
	0x07, 0x93, 0x82, 0x3e, 0x41, 0x32, 0xa4, 0xbf, 0xc2, 0xd8, 0x42, 0x55, 0xe9, 0x29, 0x6a, 0x3a,
	0x38, 0x7d, 0x37, 0x17, 0x7a, 0x07, 0x71, 0x2e, 0x4a, 0xc9, 0x73, 0x66, 0x5c, 0xd3, 0x3c, 0x42,
	0x7b, 0xd1, 0xa5, 0xd8, 0xbb, 0x82, 0xcb, 0x9e, 0xf9, 0xd6, 0x10, 0x25, 0xe9, 0x0e, 0xbe, 0x73,
	0x09, 0x84, 0x57, 0x6c, 0x67, 0xb5, 0xe0, 0x9d, 0x1d, 0x37, 0x7b, 0x7d, 0xee, 0xe9, 0x3d, 0xcc,
	0xb9, 0x92, 0x5a, 0x59, 0xd1, 0xc9, 0x09, 0xca, 0xb8, 0x8d, 0x3d, 0xbc, 0x85, 0x73, 0x5e, 0x1e,
	0xad, 0x13, 0xa6, 0x59, 0x79, 0x86, 0x6a, 0xd6, 0x66, 0xb8, 0xf1, 0x19, 0xae, 0x0f, 0x6b, 0xeb,
	0x7b, 0xb6, 0xf6, 0xa8, 0xb5, 0x32, 0x4e, 0xec, 0xd3, 0x29, 0xda, 0xe4, 0xb0, 0xb6, 0x6d, 0x5b,
	0xe6, 0x4f, 0x8b, 0x15, 0x5c, 0x0d, 0xbf, 0x17, 0xfe, 0x0d, 0xae, 0x4a, 0x3a, 0x85, 0x30, 0x77,
	0x4e, 0x93, 0x13, 0x1a, 0xc1, 0xb8, 0x7e, 0xb3, 0x24, 0x78, 0x9f, 0xfd, 0x44, 0xf5, 0xf6, 0xd7,
	0xfa, 0xb1, 0x9b, 0xa0, 0x7d, 0xf9, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x02, 0xa1, 0x3a, 0xcb,
	0x01, 0x00, 0x00,
}
