// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sm.proto

package spec

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServiceMeshes_Type int32

const (
	ServiceMeshes_appmesh            ServiceMeshes_Type = 0
	ServiceMeshes_consul             ServiceMeshes_Type = 1
	ServiceMeshes_istio              ServiceMeshes_Type = 2
	ServiceMeshes_kuma               ServiceMeshes_Type = 3
	ServiceMeshes_linkerd            ServiceMeshes_Type = 4
	ServiceMeshes_maesh              ServiceMeshes_Type = 5
	ServiceMeshes_octarine           ServiceMeshes_Type = 6
	ServiceMeshes_networkservicemesh ServiceMeshes_Type = 7
	ServiceMeshes_tanzu              ServiceMeshes_Type = 8
)

var ServiceMeshes_Type_name = map[int32]string{
	0: "appmesh",
	1: "consul",
	2: "istio",
	3: "kuma",
	4: "linkerd",
	5: "maesh",
	6: "octarine",
	7: "networkservicemesh",
	8: "tanzu",
}

var ServiceMeshes_Type_value = map[string]int32{
	"appmesh":            0,
	"consul":             1,
	"istio":              2,
	"kuma":               3,
	"linkerd":            4,
	"maesh":              5,
	"octarine":           6,
	"networkservicemesh": 7,
	"tanzu":              8,
}

func (x ServiceMeshes_Type) String() string {
	return proto.EnumName(ServiceMeshes_Type_name, int32(x))
}

func (ServiceMeshes_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e72d921038f5737c, []int{0, 0}
}

type ServiceMeshes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceMeshes) Reset()         { *m = ServiceMeshes{} }
func (m *ServiceMeshes) String() string { return proto.CompactTextString(m) }
func (*ServiceMeshes) ProtoMessage()    {}
func (*ServiceMeshes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e72d921038f5737c, []int{0}
}

func (m *ServiceMeshes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceMeshes.Unmarshal(m, b)
}
func (m *ServiceMeshes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceMeshes.Marshal(b, m, deterministic)
}
func (m *ServiceMeshes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceMeshes.Merge(m, src)
}
func (m *ServiceMeshes) XXX_Size() int {
	return xxx_messageInfo_ServiceMeshes.Size(m)
}
func (m *ServiceMeshes) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceMeshes.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceMeshes proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("SMPS.ServiceMeshes_Type", ServiceMeshes_Type_name, ServiceMeshes_Type_value)
	proto.RegisterType((*ServiceMeshes)(nil), "SMPS.ServiceMeshes")
}

func init() {
	proto.RegisterFile("sm.proto", fileDescriptor_e72d921038f5737c)
}

var fileDescriptor_e72d921038f5737c = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x24, 0x8e, 0xbd, 0x6a, 0xc3, 0x30,
	0x14, 0x85, 0xeb, 0x56, 0xb6, 0xe5, 0xeb, 0x16, 0xc4, 0x1d, 0xfa, 0x00, 0x7e, 0x80, 0x2e, 0x1d,
	0xbb, 0x75, 0x37, 0x14, 0xdc, 0xa9, 0x9b, 0xaa, 0x5c, 0xb0, 0xb0, 0xf5, 0x83, 0xae, 0x9c, 0x90,
	0x40, 0x5e, 0x21, 0xcf, 0x1c, 0xe4, 0x2c, 0x67, 0xfa, 0xbe, 0x73, 0x0e, 0x48, 0x76, 0x1f, 0x31,
	0x85, 0x1c, 0x50, 0x4c, 0xe3, 0xcf, 0x34, 0xdc, 0x2a, 0x78, 0x9b, 0x28, 0x1d, 0xad, 0xa1, 0x91,
	0x78, 0x26, 0x1e, 0xae, 0x20, 0x7e, 0xcf, 0x91, 0xb0, 0x87, 0x56, 0xc7, 0xe8, 0x88, 0x67, 0xf5,
	0x84, 0x00, 0x8d, 0x09, 0x9e, 0xb7, 0x55, 0x55, 0xd8, 0x41, 0x6d, 0x39, 0xdb, 0xa0, 0x9e, 0x51,
	0x82, 0x58, 0x36, 0xa7, 0xd5, 0x4b, 0xa1, 0x57, 0xeb, 0x17, 0x4a, 0x07, 0x25, 0x0a, 0xe1, 0x74,
	0x11, 0x6b, 0x7c, 0x05, 0x19, 0x4c, 0xd6, 0xc9, 0x7a, 0x52, 0x0d, 0xbe, 0x03, 0x7a, 0xca, 0xa7,
	0x90, 0x16, 0x7e, 0x6c, 0xee, 0xf5, 0x6d, 0x11, 0xb2, 0xf6, 0x97, 0x4d, 0xc9, 0xef, 0xfe, 0xaf,
	0xe3, 0x48, 0xe6, 0xab, 0xc4, 0x7f, 0xb3, 0x5f, 0xfd, 0xbc, 0x07, 0x00, 0x00, 0xff, 0xff, 0x35,
	0x76, 0x1e, 0x60, 0xb6, 0x00, 0x00, 0x00,
}
