// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.4
// source: traffic_metadata.proto

package spec

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TrafficMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoadBalanceName    string `protobuf:"bytes,1,opt,name=load_balance_name,json=loadBalanceName,proto3" json:"load_balance_name,omitempty"`
	LoadBalanceIp      string `protobuf:"bytes,2,opt,name=load_balance_ip,json=loadBalanceIp,proto3" json:"load_balance_ip,omitempty"`
	HostEndpoint       string `protobuf:"bytes,3,opt,name=host_endpoint,json=hostEndpoint,proto3" json:"host_endpoint,omitempty"`
	PrometheusUrl      string `protobuf:"bytes,4,opt,name=prometheus_url,json=prometheusUrl,proto3" json:"prometheus_url,omitempty"`
	HttpHeaders        string `protobuf:"bytes,5,opt,name=http_headers,json=httpHeaders,proto3" json:"http_headers,omitempty"`
	UserAgent          string `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	PingHealthEndpoint string `protobuf:"bytes,7,opt,name=ping_health_endpoint,json=pingHealthEndpoint,proto3" json:"ping_health_endpoint,omitempty"`
}

func (x *TrafficMetadata) Reset() {
	*x = TrafficMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_traffic_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrafficMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficMetadata) ProtoMessage() {}

func (x *TrafficMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficMetadata.ProtoReflect.Descriptor instead.
func (*TrafficMetadata) Descriptor() ([]byte, []int) {
	return file_traffic_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *TrafficMetadata) GetLoadBalanceName() string {
	if x != nil {
		return x.LoadBalanceName
	}
	return ""
}

func (x *TrafficMetadata) GetLoadBalanceIp() string {
	if x != nil {
		return x.LoadBalanceIp
	}
	return ""
}

func (x *TrafficMetadata) GetHostEndpoint() string {
	if x != nil {
		return x.HostEndpoint
	}
	return ""
}

func (x *TrafficMetadata) GetPrometheusUrl() string {
	if x != nil {
		return x.PrometheusUrl
	}
	return ""
}

func (x *TrafficMetadata) GetHttpHeaders() string {
	if x != nil {
		return x.HttpHeaders
	}
	return ""
}

func (x *TrafficMetadata) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *TrafficMetadata) GetPingHealthEndpoint() string {
	if x != nil {
		return x.PingHealthEndpoint
	}
	return ""
}

var File_traffic_metadata_proto protoreflect.FileDescriptor

var file_traffic_metadata_proto_rawDesc = []byte{
	0x0a, 0x16, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x53, 0x4d, 0x50, 0x22, 0xa5, 0x02,
	0x0a, 0x0f, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x2a, 0x0a, 0x11, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6c, 0x6f,
	0x61, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a,
	0x0f, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x49, 0x70, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x65, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x6f,
	0x73, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72,
	0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x55, 0x72,
	0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x74, 0x74, 0x70, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x14, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x68, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x12, 0x70, 0x69, 0x6e, 0x67, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x45, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x42, 0x0b, 0x5a, 0x09, 0x73, 0x70, 0x65, 0x63, 0x3b, 0x73, 0x70,
	0x65, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_traffic_metadata_proto_rawDescOnce sync.Once
	file_traffic_metadata_proto_rawDescData = file_traffic_metadata_proto_rawDesc
)

func file_traffic_metadata_proto_rawDescGZIP() []byte {
	file_traffic_metadata_proto_rawDescOnce.Do(func() {
		file_traffic_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_traffic_metadata_proto_rawDescData)
	})
	return file_traffic_metadata_proto_rawDescData
}

var file_traffic_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_traffic_metadata_proto_goTypes = []interface{}{
	(*TrafficMetadata)(nil), // 0: SMP.TrafficMetadata
}
var file_traffic_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_traffic_metadata_proto_init() }
func file_traffic_metadata_proto_init() {
	if File_traffic_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_traffic_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrafficMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_traffic_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_traffic_metadata_proto_goTypes,
		DependencyIndexes: file_traffic_metadata_proto_depIdxs,
		MessageInfos:      file_traffic_metadata_proto_msgTypes,
	}.Build()
	File_traffic_metadata_proto = out.File
	file_traffic_metadata_proto_rawDesc = nil
	file_traffic_metadata_proto_goTypes = nil
	file_traffic_metadata_proto_depIdxs = nil
}
