// Code generated by protoc-gen-go. DO NOT EDIT.
// source: traffic_metadata.proto

package spec

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TrafficMetadata struct {
	LoadBalanceName      string   `protobuf:"bytes,1,opt,name=load_balance_name,json=loadBalanceName,proto3" json:"load_balance_name,omitempty"`
	LoadBalanceIp        string   `protobuf:"bytes,2,opt,name=load_balance_ip,json=loadBalanceIp,proto3" json:"load_balance_ip,omitempty"`
	CalicoHostendpoint   string   `protobuf:"bytes,3,opt,name=calico_hostendpoint,json=calicoHostendpoint,proto3" json:"calico_hostendpoint,omitempty"`
	PrometheusUrl        string   `protobuf:"bytes,4,opt,name=prometheus_url,json=prometheusUrl,proto3" json:"prometheus_url,omitempty"`
	HttpHeaders          string   `protobuf:"bytes,5,opt,name=http_headers,json=httpHeaders,proto3" json:"http_headers,omitempty"`
	UserAgent            string   `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	PingHealthEndpoint   string   `protobuf:"bytes,7,opt,name=ping_health_endpoint,json=pingHealthEndpoint,proto3" json:"ping_health_endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrafficMetadata) Reset()         { *m = TrafficMetadata{} }
func (m *TrafficMetadata) String() string { return proto.CompactTextString(m) }
func (*TrafficMetadata) ProtoMessage()    {}
func (*TrafficMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_95f80f718106eaf4, []int{0}
}

func (m *TrafficMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficMetadata.Unmarshal(m, b)
}
func (m *TrafficMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficMetadata.Marshal(b, m, deterministic)
}
func (m *TrafficMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficMetadata.Merge(m, src)
}
func (m *TrafficMetadata) XXX_Size() int {
	return xxx_messageInfo_TrafficMetadata.Size(m)
}
func (m *TrafficMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficMetadata proto.InternalMessageInfo

func (m *TrafficMetadata) GetLoadBalanceName() string {
	if m != nil {
		return m.LoadBalanceName
	}
	return ""
}

func (m *TrafficMetadata) GetLoadBalanceIp() string {
	if m != nil {
		return m.LoadBalanceIp
	}
	return ""
}

func (m *TrafficMetadata) GetCalicoHostendpoint() string {
	if m != nil {
		return m.CalicoHostendpoint
	}
	return ""
}

func (m *TrafficMetadata) GetPrometheusUrl() string {
	if m != nil {
		return m.PrometheusUrl
	}
	return ""
}

func (m *TrafficMetadata) GetHttpHeaders() string {
	if m != nil {
		return m.HttpHeaders
	}
	return ""
}

func (m *TrafficMetadata) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *TrafficMetadata) GetPingHealthEndpoint() string {
	if m != nil {
		return m.PingHealthEndpoint
	}
	return ""
}

func init() {
	proto.RegisterType((*TrafficMetadata)(nil), "SMPS.TrafficMetadata")
}

func init() {
	proto.RegisterFile("traffic_metadata.proto", fileDescriptor_95f80f718106eaf4)
}

var fileDescriptor_95f80f718106eaf4 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x46, 0x69, 0xad, 0x95, 0x9d, 0xaa, 0x8b, 0x51, 0x24, 0x17, 0x41, 0x05, 0x45, 0x3c, 0xa8,
	0xe0, 0xd1, 0x93, 0x05, 0x61, 0x3d, 0x54, 0xc4, 0xea, 0xc5, 0x4b, 0x98, 0xee, 0x4e, 0xbb, 0x0b,
	0xd9, 0x24, 0x64, 0x67, 0x7f, 0x98, 0xff, 0x50, 0x92, 0x14, 0x6d, 0x2f, 0x39, 0xbc, 0xf7, 0x18,
	0x3e, 0x02, 0xa7, 0xec, 0x71, 0xb9, 0x6c, 0x4a, 0xd5, 0x12, 0x63, 0x85, 0x8c, 0x77, 0xce, 0x5b,
	0xb6, 0x62, 0x34, 0x9f, 0xbd, 0xcf, 0x2f, 0x7f, 0x86, 0x90, 0x7f, 0xa6, 0x60, 0xb6, 0xf6, 0xe2,
	0x16, 0x8e, 0xb4, 0xc5, 0x4a, 0x2d, 0x50, 0xa3, 0x29, 0x49, 0x19, 0x6c, 0x49, 0x0e, 0xce, 0x07,
	0x37, 0xd9, 0x47, 0x1e, 0xc4, 0x34, 0xf1, 0x37, 0x6c, 0x49, 0x5c, 0x43, 0xbe, 0xd5, 0x36, 0x4e,
	0x0e, 0x63, 0x79, 0xb0, 0x51, 0xbe, 0x3a, 0x71, 0x0f, 0xc7, 0x25, 0xea, 0xa6, 0xb4, 0xaa, 0xb6,
	0x1d, 0x93, 0xa9, 0x9c, 0x6d, 0x0c, 0xcb, 0x9d, 0xd8, 0x8a, 0xa4, 0x8a, 0x0d, 0x23, 0xae, 0xe0,
	0xd0, 0x79, 0xdb, 0x12, 0xd7, 0xd4, 0x77, 0xaa, 0xf7, 0x5a, 0x8e, 0xd2, 0xdd, 0x7f, 0xfa, 0xe5,
	0xb5, 0xb8, 0x80, 0xfd, 0x9a, 0xd9, 0xa9, 0x9a, 0xb0, 0x22, 0xdf, 0xc9, 0xdd, 0x18, 0x4d, 0x02,
	0x2b, 0x12, 0x12, 0x67, 0x00, 0x7d, 0x47, 0x5e, 0xe1, 0x8a, 0x0c, 0xcb, 0x71, 0x0c, 0xb2, 0x40,
	0x9e, 0x03, 0x10, 0x0f, 0x70, 0xe2, 0x1a, 0xb3, 0x0a, 0x17, 0x34, 0xd7, 0xea, 0x6f, 0xda, 0x5e,
	0x9a, 0x16, 0x5c, 0x11, 0xd5, 0xcb, 0xda, 0x4c, 0x27, 0xdf, 0x59, 0xe7, 0xa8, 0x7c, 0x0a, 0xcf,
	0x62, 0x1c, 0x7f, 0xf3, 0xf1, 0x37, 0x00, 0x00, 0xff, 0xff, 0x70, 0x62, 0x22, 0x57, 0x67, 0x01,
	0x00, 0x00,
}
