#after any changes to the Gemfile, execute bundle update!
source "https://rubygems.org"
gemspec
group :jekyll_plugins do
    gem "jekyll-feed"
    gem "jekyll-paginate"
    gem "jekyll-sitemap"
    gem 'jekyll-manager' if ENV['ADMIN'] == 'on'
  end

# Delete the following lines if not on Windows:
# Performance-booster for watching directories on Windows
gem "wdm", ">= 0.1.0" if Gem.win_platform?
