#after any changes to the Gemfile, execute bundle update!
source "https://rubygems.org"

group :jekyll_plugins do
    gem "jekyll-feed"
    gem "jekyll-paginate"
    gem "jekyll-sitemap"
    # gem "jekyll-seo-tag"
    gem 'jemoji', '~> 0.12.0'
    gem "nokogiri", ">= 1.11.0.rc4"
    gem 'jekyll-coffeescript', '~> 2.0'
    gem 'jekyll-manager' if ENV['ADMIN'] == 'on'
  end

# Delete the following lines if not on Windows:
# Performance-booster for watching directories on Windows
gem "wdm", ">= 0.1.0" if Gem.win_platform?
